<a href="https://colab.research.google.com/github/carissafarry/study-ml/blob/main/3.1%20Complete%20Numpy%20Tutorial%20in%20Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy - Numerical Python

Advantages of Numpy Arrays:
1. Allows several Mathematical Operations
2. Faster operations

In [1]:
import numpy as np

#List vs Numpy - Time Taken

In [2]:
from time import process_time

Time taken by a list

In [4]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [1+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.000506885000000068


In [6]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5 

end_time = process_time()

print(end_time - start_time)

0.0009231579999999795


#Numpy Arrays

In [7]:
# list
l1 = [1,2,3,4,5]
print(l1)
type(l1)

[1, 2, 3, 4, 5]


list

In [8]:
np_ar = np.array([1,2,3,4,5])
print(np_ar)
type(np_ar)

[1 2 3 4 5]


numpy.ndarray

In [9]:
# creating a 1 dimension array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [10]:
a.shape

(4,)

In [11]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [13]:
c = np.array(b,dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


#Initial Placeholders in numpy arrays

In [14]:
# cretae a numpy array of zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [18]:
# create an identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.01300233 0.29835719 0.29646303 0.65035492]
 [0.35900219 0.24810819 0.43198744 0.78269707]
 [0.10956508 0.45070608 0.51368738 0.49303503]]


In [20]:
# random integer values array within a spesific range
c = np.random.randint(10,100,(3,5))
print(c)

[[88 85 56 67 57]
 [83 46 91 64 18]
 [77 26 84 26 65]]


In [25]:
# array of evenly spaced value (jarak angka tertentu) (mendefinisikan jumlah angka keluar yang diminta)
d = np.linspace(10,30,3)
print(d)

[10. 20. 30.]


In [24]:
# array of evenly spaced values --> specifying the step (mendefinisikan jaraknya)
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [26]:
# convert a list to a numpy array
l2 = [10,20,30,40,50]
np_ar = np.asarray(l2)
print(np_ar)
type(np_ar)

[10 20 30 40 50]


numpy.ndarray

In [27]:
  # Analysing a numpy array
  c = np.random.randint(10,90,(5,5))
  print(c)

[[18 62 61 51 66]
 [26 67 80 27 48]
 [38 27 26 65 50]
 [27 19 49 57 41]
 [68 26 66 27 11]]


In [28]:
# array dimension
print(c.shape)

(5, 5)


In [29]:
# number of dimensions
print(c.ndim)

2


In [30]:
# number of elements in an array
print(c.size)

25


In [31]:
# checking the data type of the values in the array
print(c.dtype)

int64


#Mathematical operations on a np array

In [32]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,10]

print(l1+l2)  # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [40]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [41]:
print(a)
print(b)

[[3 1 2]
 [3 1 3]
 [0 0 8]]
[[17 17 19]
 [13 12 12]
 [19 18 14]]


In [42]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[20 18 21]
 [16 13 15]
 [19 18 22]]
[[-14 -16 -17]
 [-10 -11  -9]
 [-19 -18  -6]]
[[ 51  17  38]
 [ 39  12  36]
 [  0   0 112]]
[[0.17647059 0.05882353 0.10526316]
 [0.23076923 0.08333333 0.25      ]
 [0.         0.         0.57142857]]


In [43]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[20 18 21]
 [16 13 15]
 [19 18 22]]
[[-14 -16 -17]
 [-10 -11  -9]
 [-19 -18  -6]]
[[ 51  17  38]
 [ 39  12  36]
 [  0   0 112]]
[[0.17647059 0.05882353 0.10526316]
 [0.23076923 0.08333333 0.25      ]
 [0.         0.         0.57142857]]


#Array Manipulation

In [44]:
ar = np.random.randint(0,10,(2,3))
print(ar)
print(ar.shape)

[[9 5 3]
 [1 0 7]]
(2, 3)


In [45]:
# transpose
tp = np.transpose(ar)
print(tp)
print(tp.shape)

[[9 1]
 [5 0]
 [3 7]]
(3, 2)


In [46]:
ar2 = np.random.randint(0,10,(2,3))
print(ar2)
print(ar2.shape)

[[2 4 7]
 [1 6 6]]
(2, 3)


In [48]:
tp2 = ar2.T
print(tp2)
print(tp2.shape)

[[2 1]
 [4 6]
 [7 6]]
(3, 2)


In [49]:
# reshaping an array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[6 7 0]
 [3 2 4]]
(2, 3)


In [50]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[6 7]
 [0 3]
 [2 4]]
(3, 2)
